# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: potluck_new_app
  username: root
  password: root
  host: 127.0.0.1

production:
  adapter: mysql2
  database: potluck_new_app
  username: root
  password: root
  host: 127.0.0.1
